openapi: "3.0.2"
info:
  description: This is a sample server power of attorney service
  version: 1.0.0
  title: Power of attorney
  license:
    name: GNU
servers:
  - url: http://localhost:8080

paths:
  /accounts:
    put:
      summary: Create Account
      description: Create Account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        "201":
          description: Account successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"

  /accounts/{id}:
    get:
      summary: Get Details of an Account
      description: Get Details of an Account
      operationId: getAccount
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Account found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /accounts/{id}/deposit:
    post:
      summary: Deposit Money onto an account
      description: Deposit Money onto an account
      operationId: deposit
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        "200":
          description: Money Deposited
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /accounts/{id}/withdraw:
    post:
      summary: Withdraw money from an account
      description:  Withdraw money from an account
      operationId: withdraw
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
      responses:
        "200":
          description: Money Deposited
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /accounts/{id}/transactions:
    get:
      summary: List transactions
      description:  List transactions
      operationId: transactions
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of transactions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transactions"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"


components:
  schemas:

    ErrorObject:
      type: object
      required:
        - code
        - message
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string

    CreateAccountRequest:
      type: object
      required:
        - customerId
        - accountType
        - created
      properties:
        customerId:
          type: string
          format: uuid
          example: b13fd77c-6243-4b1e-9a8d-b8494f621418
        accountType:
          $ref: "#/components/schemas/AccountType"
        created:
          type: string
          format: date

    DepositRequest:
      type: object
      required:
        - amount
        - created
      properties:
        amount:
          type: number
          format: double
          minimum: 0.0
        created:
          type: string
          format: date

    WithdrawRequest:
      type: object
      required:
        - amount
        - created
      properties:
        amount:
          type: number
          format: double
          minimum: 0.0
        created:
          type: string
          format: date

    Account:
      type: object
      required:
        - accountNumber
        - balance
        - customerId
        - accountType
        - created
      properties:
        accountNumber:
          type: string
          format: uuid
          example: b13fd77c-6243-4b1e-9a8d-b8494f621418
        balance:
          type: number
          format: double
        lastTransactionAmount:
          type: number
          format: double
        customerId:
          type: string
          format: uuid
        accountType:
          $ref: "#/components/schemas/AccountType"
        created:
          type: string
          format: date

    Transactions:
      type: object
      required:
        - accountNumber
      properties:
        accountNumber:
          type: string
          format: uuid
          example: b13fd77c-6243-4b1e-9a8d-b8494f621418
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/Transaction"

    Transaction:
      type: object
      required:
        - balance
        - created
      properties:
        balance:
          type: number
          format: double
        transactionAmount:
          type: number
          format: double

    AccountType:
      type: string
      enum:
        - SAVINGS